// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gorkagg10/equity-calculator-api/internal/domain (interfaces: PortfolioRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_repositories.go -package=domain . PortfolioRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPortfolioRepository is a mock of PortfolioRepository interface.
type MockPortfolioRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioRepositoryMockRecorder
	isgomock struct{}
}

// MockPortfolioRepositoryMockRecorder is the mock recorder for MockPortfolioRepository.
type MockPortfolioRepositoryMockRecorder struct {
	mock *MockPortfolioRepository
}

// NewMockPortfolioRepository creates a new mock instance.
func NewMockPortfolioRepository(ctrl *gomock.Controller) *MockPortfolioRepository {
	mock := &MockPortfolioRepository{ctrl: ctrl}
	mock.recorder = &MockPortfolioRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioRepository) EXPECT() *MockPortfolioRepositoryMockRecorder {
	return m.recorder
}

// AddPortfolio mocks base method.
func (m *MockPortfolioRepository) AddPortfolio(ctx context.Context, portfolio *Portfolio) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPortfolio", ctx, portfolio)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPortfolio indicates an expected call of AddPortfolio.
func (mr *MockPortfolioRepositoryMockRecorder) AddPortfolio(ctx, portfolio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPortfolio", reflect.TypeOf((*MockPortfolioRepository)(nil).AddPortfolio), ctx, portfolio)
}

// FindByID mocks base method.
func (m *MockPortfolioRepository) FindByID(ctx context.Context, portfolioID uuid.UUID) (*Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, portfolioID)
	ret0, _ := ret[0].(*Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPortfolioRepositoryMockRecorder) FindByID(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPortfolioRepository)(nil).FindByID), ctx, portfolioID)
}
